import os
#please modify the path for your own path
root = '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/'
join = os.path.join
model_fold = {'resnet1d': {'bcg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-resnet1d/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-resnet1d/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-resnet1d/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-resnet1d/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-resnet1d/fold4.ckpt'},
  'ppgbp': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-resnet1d/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-resnet1d/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-resnet1d/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-resnet1d/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-resnet1d/fold4.ckpt'},
  'sensors': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-resnet1d/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-resnet1d/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-resnet1d/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-resnet1d/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-resnet1d/fold4.ckpt'},
  'mimic_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-resnet1d/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-resnet1d/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-resnet1d/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-resnet1d/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-resnet1d/fold4.ckpt'},
  'vital_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-resnet1d/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-resnet1d/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-resnet1d/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-resnet1d/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-resnet1d/fold4.ckpt'}},
 'mlpbp': {'bcg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-mlpbp/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-mlpbp/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-mlpbp/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-mlpbp/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-mlpbp/fold4.ckpt'},
  'ppgbp': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-mlpbp/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-mlpbp/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-mlpbp/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-mlpbp/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-mlpbp/fold4.ckpt'},
  'sensors': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-mlpbp/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-mlpbp/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-mlpbp/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-mlpbp/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-mlpbp/fold4.ckpt'},
  'mimic_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-mlpbp/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-mlpbp/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-mlpbp/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-mlpbp/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-mlpbp/fold4.ckpt'},
  'vital_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-mlpbp/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-mlpbp/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-mlpbp/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-mlpbp/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-mlpbp/fold4.ckpt'}},
 'bptransformer': {'bcg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-bptransformer/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-bptransformer/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-bptransformer/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-bptransformer/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-bptransformer/fold4.ckpt'},
  'ppgbp': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-bptransformer/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-bptransformer/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-bptransformer/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-bptransformer/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-bptransformer/fold4.ckpt'},
  'sensors': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-bptransformer/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-bptransformer/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-bptransformer/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-bptransformer/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-bptransformer/fold4.ckpt'},
  'mimic_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-bptransformer/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-bptransformer/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-bptransformer/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-bptransformer/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-bptransformer/fold4.ckpt'},
  'vital_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-bptransformer/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-bptransformer/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-bptransformer/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-bptransformer/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-bptransformer/fold4.ckpt'}},
 'spectroresnet': {'bcg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-spectroresnet/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-spectroresnet/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-spectroresnet/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-spectroresnet/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/bcg-spectroresnet/fold4.ckpt'},
  'ppgbp': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-spectroresnet/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-spectroresnet/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-spectroresnet/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-spectroresnet/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/ppgbp-spectroresnet/fold4.ckpt'},
  'sensors': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-spectroresnet/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-spectroresnet/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-spectroresnet/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-spectroresnet/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/sensors-spectroresnet/fold4.ckpt'},
  'mimic_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-spectroresnet/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-spectroresnet/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-spectroresnet/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-spectroresnet/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/mimic_ecg-spectroresnet/fold4.ckpt'},
  'vital_ecg': {0: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-spectroresnet/fold0.ckpt',
   1: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-spectroresnet/fold1.ckpt',
   2: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-spectroresnet/fold2.ckpt',
   3: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-spectroresnet/fold3.ckpt',
   4: '/data1/bubble3jh/bp_L2P/code/train/pretrained_models/vital_ecg-spectroresnet/fold4.ckpt'}}}