wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718078524
    t:
      1:
      - 1
      - 5
      - 8
      - 9
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 9
      - 50
      - 53
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.19
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
config_file:
  desc: null
  value: core/config/dl/resnet/resnet_sensors.yaml
lr:
  desc: null
  value: 0.1
wd:
  desc: null
  value: 0.01
global_coeff:
  desc: null
  value: 5.0
gen_coeff:
  desc: null
  value: 1.0
method:
  desc: null
  value: prompt_global
root_dir:
  desc: null
  value: ./
result_dirname:
  desc: null
  value: results
layer_num:
  desc: null
  value: 0
glonorm:
  desc: null
  value: false
normalize:
  desc: null
  value: true
clip:
  desc: null
  value: false
seed:
  desc: null
  value: 0
group_avg:
  desc: null
  value: false
penalty:
  desc: null
  value: false
k:
  desc: null
  value: 1
num_pool:
  desc: null
  value: 10
mul:
  desc: null
  value: false
fixed_key:
  desc: null
  value: false
fixed_prompt:
  desc: null
  value: false
trans:
  desc: null
  value: false
ignore_wandb:
  desc: null
  value: false
count_group:
  desc: null
  value: false
data_root:
  desc: null
  value: /bp_benchmark/datasets/ETRI_2023/results
use_group:
  desc: null
  value: false
train_head:
  desc: null
  value: false
reset_head:
  desc: null
  value: false
backbone:
  desc: null
  value: resnet1d
shots:
  desc: null
  value: 5
transfer:
  desc: null
  value: ppgbp
target:
  desc: null
  value: sensors
prompt_weights:
  desc: null
  value: attention
penalty_scaler:
  desc: null
  value: 0.0
qk_sim_coeff:
  desc: null
  value: 0.0
pca_dim:
  desc: null
  value: 20
query_dim:
  desc: null
  value: 256
batch_size:
  desc: null
  value: 4
weight_per_prompt:
  desc: null
  value: false
lp:
  desc: null
  value: false
scratch:
  desc: null
  value: false
epochs:
  desc: null
  value: 10
num_patience:
  desc: null
  value: 100
lam:
  desc: null
  value: 0.5
