#!/bin/bash

# e27vgfil
CUDA_VISIBLE_DEVICES=0 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target ppgbp --get_emb False --glonorm False --pca_dim 64 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head False --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 9ptlrtzq
CUDA_VISIBLE_DEVICES=1 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target sensors --get_emb False --glonorm False --pca_dim 32 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 23kphaty
CUDA_VISIBLE_DEVICES=2 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target vital_ecg --get_emb False --glonorm False --pca_dim 16 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer mimic_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head False --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_mimic_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 7m1ltxpa
CUDA_VISIBLE_DEVICES=3 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target bcg --get_emb False --glonorm False --pca_dim 64 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 88lvqagu
CUDA_VISIBLE_DEVICES=4 python train.py --k 1 --lr 0.1 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target sensors --get_emb False --glonorm False --pca_dim 64 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# gxgveqrp
CUDA_VISIBLE_DEVICES=5 python train.py --k 1 --lr 0.01 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target bcg --get_emb False --glonorm False --pca_dim 32 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 152zjw6r
CUDA_VISIBLE_DEVICES=6 python train.py --k 1 --lr 0.01 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target ppgbp --get_emb False --glonorm False --pca_dim 64 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 1hc9fqo7
CUDA_VISIBLE_DEVICES=7 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method prompt_global --target mimic_ecg --get_emb False --glonorm False --pca_dim 16 --penalty False --add_freq True --backbone bptransformer --baseline ft --instance False --num_pool 4 --pass_pca True --root_dir ./ --transfer vital_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 64 --trunc_dim 25 --use_group False --batch_size 6 --reset_head False --stepbystep True --sym_prompt True --train_head True --train_imag True --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_vital_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0 --use_emb_diff True --penalty_scaler 0 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# hq0t8zav
CUDA_VISIBLE_DEVICES=0 python train.py --k 1 --lr 0.0001 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# iqrlv0vp
CUDA_VISIBLE_DEVICES=1 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 4qtab1ve
CUDA_VISIBLE_DEVICES=2 python train.py --k 1 --lr 0.0001 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target vital_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer mimic_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_mimic_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# bnrfrmcs
CUDA_VISIBLE_DEVICES=3 python train.py --k 1 --lr 0.0001 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# g3r4f5g6
CUDA_VISIBLE_DEVICES=4 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 3s47lhwz
CUDA_VISIBLE_DEVICES=5 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# p2d6yvs6
CUDA_VISIBLE_DEVICES=6 python train.py --k 1 --lr 0.01 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# r7ozw7u7
CUDA_VISIBLE_DEVICES=7 python train.py --k 1 --lr 0.0001 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target mimic_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone bptransformer --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer vital_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/bptransformer/bptransformer_vital_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 5gn9yuld
CUDA_VISIBLE_DEVICES=0 python train.py --k 1 --lr 0.0001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 8mafbd9u
CUDA_VISIBLE_DEVICES=1 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# i37o0d2e
CUDA_VISIBLE_DEVICES=2 python train.py --k 1 --lr 0.0001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target vital_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer mimic_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_mimic_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# zxywqunl
CUDA_VISIBLE_DEVICES=3 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 99046yae
CUDA_VISIBLE_DEVICES=4 python train.py --k 1 --lr 0.001 --wd 0.001 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# jq47be1o
CUDA_VISIBLE_DEVICES=5 python train.py --k 1 --lr 0.001 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 1uc5mm4b
CUDA_VISIBLE_DEVICES=6 python train.py --k 1 --lr 0.0001 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# jkte6o9e
CUDA_VISIBLE_DEVICES=7 python train.py --k 1 --lr 0.0001 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target mimic_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone mlpbp --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer vital_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/mlpbp/mlpbp_vital_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 721ddut6
CUDA_VISIBLE_DEVICES=0 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 2d1vpo59
CUDA_VISIBLE_DEVICES=1 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# imlxavbh
CUDA_VISIBLE_DEVICES=2 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target vital_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer mimic_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_mimic_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# z8ar45wh
CUDA_VISIBLE_DEVICES=3 python train.py --k 1 --lr 0.001 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 29ji834k
CUDA_VISIBLE_DEVICES=4 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# uys13zz6
CUDA_VISIBLE_DEVICES=5 python train.py --k 1 --lr 0.01 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# puwiocm4
CUDA_VISIBLE_DEVICES=6 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 4wxuaafs
CUDA_VISIBLE_DEVICES=7 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target mimic_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone resnet1d --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer vital_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/resnet/resnet_vital_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# naucf5pn
CUDA_VISIBLE_DEVICES=0 python train.py --k 1 --lr 0.1 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# aicdguab
CUDA_VISIBLE_DEVICES=1 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer bcg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_bcg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# 6njr55tx
CUDA_VISIBLE_DEVICES=2 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target vital_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer mimic_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_mimic_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# uh5rxiuv
CUDA_VISIBLE_DEVICES=3 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# vpgzo23v
CUDA_VISIBLE_DEVICES=4 python train.py --k 1 --lr 0.1 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target sensors --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer ppgbp --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_ppgbp.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# gg6u1pk8
CUDA_VISIBLE_DEVICES=5 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target bcg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# ogrg338j
CUDA_VISIBLE_DEVICES=6 python train.py --k 1 --lr 0.1 --wd 0.01 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target ppgbp --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer sensors --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_sensors.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

# nhfee6d6
CUDA_VISIBLE_DEVICES=7 python train.py --k 1 --lr 0.01 --wd 0.1 --lam 1 --mul False --clip False --seed 0 --shots 5 --trans False --epochs 10 --method original --target mimic_ecg --get_emb False --glonorm False --pca_dim 20 --penalty False --add_freq False --backbone spectroresnet --baseline ft --instance False --num_pool 10 --pass_pca False --root_dir ./ --transfer vital_ecg --data_root /bp_benchmark/datasets/ETRI_2023/results --fixed_key False --gen_coeff 1 --group_avg False --layer_num 0 --normalize False --query_dim 32 --trunc_dim 50 --use_group False --batch_size 6 --reset_head False --stepbystep False --sym_prompt True --train_head False --train_imag False --use_pt_emb False --add_prompts None --config_file core/config/dl/spectroresnet/spectroresnet_vital_ecg.yaml --count_group False --save_result False --fixed_prompt False --global_coeff 1 --ignore_wandb False --num_patience 100 --qk_sim_coeff 0.5 --use_emb_diff False --penalty_scaler 0.1 --prompt_weights learnable --result_dirname results --diff_loss_weight 1 --pen_prompt_coeff 1 --weight_per_prompt False --wandb_project_name mqfp --save_for_pretraining False &

