path:
  model_directory: ./model-${exp.model_type}
  mlflow_dir: ./mlruns
exp:
  fs: 125
  N_fold: 5
  random_state: 100
  data_name: ppgbp
  model_type: bptransformer
  exp_name: ${exp.data_name}-${exp.model_type}
  subject_dict: /mlainas/ETRI_2023/splitted/${exp.data_name}_dataset/signal_fold
  loader: waveform
  cv: cv
param_loader:
  ppg_norm: loc_z
  bp_norm: glob_mm
objective:
  type: val_mse
  mode: min
param_test:
  save_path: /sensorsbp/prediction/ppgbp_dataset/rsnt_ppgbp_nobw.pkl
param_trainer:
  max_epochs: 100
  check_val_every_n_epoch: 2
  progress_bar_refresh_rate: 5
  gpus: '0'
  auto_lr_find: true
  auto_scale_batch_size: binsearch
param_early_stop:
  monitor: ${objective.type}
  min_delta: 0.0
  patience: 1000
  verbose: true
  mode: ${objective.mode}
param_model:
  N_epoch: 256
  batch_size: 32
  in_channel: 1
  base_filters: 32
  first_kernel_size: 9
  kernel_size: 5
  stride: 4
  groups: 2
  n_block: 4
  output_size: 2
  lr: 0.001
  sample_step: 1
  is_se: true
  se_ch_low: 4
  num_encoder_layers: 2
  num_decoder_layers: 2
  dim_model: 512                 
  input_feature_dim: 1          
  demographic_feature_dim: 0    
  dropout: 0.1
  n_heads: 4
  hidden_dim: 64
logger:
  param_ckpt:
    monitor: ${objective.type}
    filename: '{epoch:02d}-{${objective.type}:.3f}'
    save_top_k: 1
    mode: ${objective.mode}
