param_model:
  N_epoch: 256
  batch_size: 256
  in_channel: 1
  base_filters: 32
  first_kernel_size: 5
  kernel_size: 3
  stride: 4
  groups: 2
  n_block: 8
  output_size: 2
  lr: 0.01
  sample_step: 1
  is_se: true
  se_ch_low: 4
  wd: 0
random_state: 300
pos_weight: null
